backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Inlägg" # Used in the UI, ie.: "New Post"
    folder: "tvb-mod/content/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Publicera", name: "date", widget: "datetime"}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Text", name: "body", widget: "markdown"}
